### ISSUE TITLE
Enhancement/toy idea: ability to play simple tunes using the keyboard

### ISSUE THREAD

**Issue by Piciok** [davidacm/enhancedTones#2]
Hello!

I know this idea is the last thing that is needed but the concept of multiple alternative tone generators inspired me to share it anyway.
My suggestion is also partly based on the [Tone Master Addon](https://github.com/hkatic/toneMaster), which I find a great idea but firstly, it doesn't seem to be maintained a lot and secondly, I was never very good at calculating tone lengths and highs to achieve what I needed.
Sometimes I find myself in need of quickly throwing a melody together by simply pressing some keys, E.G. to let a tune that's stuck in my head out or to create a short jingle/ringtone in retro style. I am not an expert musician but I can play a little tune by ear if I try hard enough to find the right sounds. I am also a fan of the 90's monophonic aesthetic and enjoy the sound of old phone ringtones, computer game music etc. so I was on a search for a simple tool that would allow me to jam a little bit in that style.
I know that what I want to achieve is already possible with Midi sequencers and an array of VST instruments but I would like to start with something that offers the bare minimum to maybe gradually move on to more advanced solutions.
So far my closest matches to what I'm looking for are the following websites which emulate the old Nokia composer:
https://github.com/zserge/nokia-composer
https://github.com/eddmann/nokia-composer-web
https://github.com/DarkoKukovec/retro-composer
Unfortunately, these web-based solutions present some limitations such as not all the keys working in all the browsers and an NVDA addon, however toy'esque, would offer a handy solution to achieve this task.
The ability to record these melodies into an audio file would be a great addition but if it poses too much difficulty, there are ways to record the played melody anyway.

I hope you will find the capacity to consider my suggestion. Thank you for all of your work.

**Comment by davidacm** [comment]
Hi @Piciok,

Implementing such a feature would be outside the capabilities of the add-on, even the tasks a screen reader is supposed to do. Anyway, The idea would need a separate add-on. Maybe in the future...

Currently, I do not have the required time to develop it because I'm involved in several projects and my professional job. We could work on the existing solutions, and improve or make accessible what is needed.

I'm closing this issue because I can't implement it on this add-on.

Best regards,
David CM.
